# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "arkencrab"
description = "Experimental arkenfox toolbox"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anstream = "0.6.20"
chrono = { version = "0.4.42", default-features = false, features = ["std", "clock"] }
clap = { version = "4.5.48", features = ["derive", "env"] }
clap_complete = "4.5.58"
color-eyre = { version = "0.6.5", default-features = false }
eyre = "0.6.12"
owo-colors = "4.2.2"
regex = "1.11.2"
rust-ini = "0.21.3"
reqwest = { version = "0.12.23", features = ["blocking", "charset", "http2", "macos-system-configuration", "rustls-tls-webpki-roots", "gzip", "brotli", "zstd"], default-features = false }
similar = "2.7.0"
shlex = "1.3.0"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

redundant_closure_for_method_calls = "allow"
